version: "2"

services:
  php:
    environment:
      PHP_FPM_CLEAR_ENV: "no"
      PHP_XHPROF: 1
      #PHP_XDEBUG: 1
      #PHP_XDEBUG_DEFAULT_ENABLE: 1
    volumes:
      - ./:/var/www/html

  nginx:
    volumes:
      - ./:/var/www/html

  mariadb:
    volumes:
      - ../database:/var/lib/mysql

  traefik:
    ports:
      - '80:80'
